/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALCULADORA_H_RPCGEN
#define _CALCULADORA_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct args {
	float num1;
	float num2;
};
typedef struct args args;

#define CALCULADORA 0x30000001
#define CALCULADORA_VER 1

#if defined(__STDC__) || defined(__cplusplus)
#define sumar 1
extern  float * sumar_1(args *, CLIENT *);
extern  float * sumar_1_svc(args *, struct svc_req *);
#define restar 2
extern  float * restar_1(args *, CLIENT *);
extern  float * restar_1_svc(args *, struct svc_req *);
#define multiplicar 3
extern  float * multiplicar_1(args *, CLIENT *);
extern  float * multiplicar_1_svc(args *, struct svc_req *);
#define dividir 4
extern  float * dividir_1(args *, CLIENT *);
extern  float * dividir_1_svc(args *, struct svc_req *);
extern int calculadora_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define sumar 1
extern  float * sumar_1();
extern  float * sumar_1_svc();
#define restar 2
extern  float * restar_1();
extern  float * restar_1_svc();
#define multiplicar 3
extern  float * multiplicar_1();
extern  float * multiplicar_1_svc();
#define dividir 4
extern  float * dividir_1();
extern  float * dividir_1_svc();
extern int calculadora_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_args (XDR *, args*);

#else /* K&R C */
extern bool_t xdr_args ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CALCULADORA_H_RPCGEN */
