/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculadora.h"
#include <stdio.h>

float *
sumar_1_svc(args *argp, struct svc_req *rqstp)
{
	static float result;

	/*
	 * insert server code here
	 */
	result = argp->num1 + argp->num2;
	printf("Se hizo una suma\n");
	return &result;
}

float *
restar_1_svc(args *argp, struct svc_req *rqstp)
{
	static float result;

	/*
	 * insert server code here
	 */
	result = argp->num1 - argp->num2;
	printf("Se hizo una resta\n");
	return &result;
}

float *
multiplicar_1_svc(args *argp, struct svc_req *rqstp)
{
	static float result;

	/*
	 * insert server code here
	 */
	result = argp->num1 * argp->num2;
	printf("Se hizo una multiplicación\n");
	return &result;
}

float *
dividir_1_svc(args *argp, struct svc_req *rqstp)
{
	static float result;

	/*
	 * insert server code here
	 */
	result = argp->num1 / argp->num2;
	printf("Se hizo una división\n");
	return &result;
}
